------------------------------------------------------------------------------------------------------------
-------------------------------- Project Developed by // TUSHAR SRIVASTAVA ---------------------------------
--------------------- Hire Me // Mobile No.: 8299357488 && Email: tusharrbl@gmail.com ----------------------
---------------------------- Portfolio // https://www.tusharsrivastava.tech --------------------------------
-------------------------- LinkedIn // https://www.linkedin.com/in/tusharrblgh -----------------------------
----------------------------- GitHub // https://www.github.com/tusharrblgh ---------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------ ⚠️ Legal Notice – Copyright Warning (India) --------------------------------
-------- This project is protected under the Copyright Act, 1957 (as amended) and other applicable ---------
--------------------------------- intellectual property laws of India. -------------------------------------
------------------ Any unauthorized copying, reproduction, modification, distribution, or ------------------
-------------------------- commercial use of this work, in whole or in part, -------------------------------
------------ without the explicit written permission of the author is strictly prohibited. -----------------
------------------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: github-id/boardgame:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer # type of the service.